### ISSUE TITLE
Add mer OBS webhook

### ISSUE THREAD

**Issue by r0kk3rz** [Sailbook/harbour-matrix#12]
We can have automatic builds on Mer OBS if we set up webhooks.

To do this open up your Github repository and go to Settings > Webhooks & Services > Add a Webhook.

Use https://webhook.merproject.org/webhook/ as the Payload URL

These following items should be set to default, but just check: 
Content type should be application/json
Enable SSL verification
Enable Just the push event
Enable Active

**Comment by Sailbook** [comment]
Ok done ;)

**Comment by r0kk3rz** [comment]
FYI: every time you tag a release it will be built on here:
https://build.merproject.org/package/show/home:r0kk3rz/harbour-matrix
