### ISSUE TITLE
Translations is broke.   

### ISSUE THREAD

**Issue by Caballlero** [Sailbook/harbour-matrix#14]
Translations on matriksi not working.
- Also matriksi is sending .ts files to **usr/share/matriksi/translations** which has to be just .qm
![captura_20171118_001](https://user-images.githubusercontent.com/24536606/32980916-1927cd9a-cc3d-11e7-8141-0c3c9cd20c30.png)

- Actually there are 2 files on spanish translations. Can you please delete the: harbour-matrix-es.ts to preven conflicts.
Thanks ...

**Comment by Sailbook** [comment]
Ok done....
