### ISSUE TITLE
Compile errors into messageeventmodel.cpp

### ISSUE THREAD

**Issue by Sailbook** [Sailbook/harbour-matrix#3]
Compile errors into messageeventmodel.cpp any help would be welcome...

void MessageEventModel::changeRoom(QMatrixClient::Room* room)
{
    beginResetModel();
    if( m_currentRoom )
    {
        m_currentRoom->disconnect(this);
    }
    m_currentRoom = room;
    if( room )
    {
        using namespace QMatrixClient;
        connect( room, &Room::aboutToAddNewMessages,
                [=](const Events& events)
                {
                    beginInsertRows(QModelIndex(), 0, events.size() - 1);
                });
        connect( room, &Room::aboutToAddHistoricalMessages,
                [=](const Events& events)
                {
                    beginInsertRows(QModelIndex(),
                                    rowCount(), rowCount() + events.size() - 1);
                });
        connect( room, &Room::addedMessages,
                 this, &MessageEventModel::endInsertRows );
        qDebug() << "connected" << room;
    }
    endResetModel();
}

**Comment by r0kk3rz** [comment]
The models on this fork of tensor are much more up to date:
https://github.com/Quiark/tensor/tree/master/client/models

You should be able to just copy them as is

**Comment by Sailbook** [comment]
Hi,
I just try it but i got a lot of compile errors...
Here you have a screenshot:
https://imgur.com/a/SVmR3
